use std::path::Path;

use wasm_manifest::Lockfile;
use wasm_package_manager::Reference;

/// Parse an OCI reference string, stripping the optional `oci://` scheme prefix.
///
/// Accepts both bare references (e.g. `ghcr.io/owner/repo:tag`) and
/// references with the `oci://` scheme (e.g. `oci://ghcr.io/owner/repo:tag`).
pub(crate) fn parse_reference(s: &str) -> Result<Reference, String> {
    let s = s.strip_prefix("oci://").unwrap_or(s);
    s.parse::<Reference>().map_err(|e| e.to_string())
}

/// Convert an [`anyhow::Error`] into a [`miette::Report`], preserving the
/// cause chain.
///
/// This bridges subsystems that still return [`anyhow::Error`] with the
/// top-level CLI that uses [`miette`] for rich error display.
#[allow(dead_code, clippy::needless_pass_by_value)]
pub(crate) fn into_miette(err: anyhow::Error) -> miette::Report {
    // Use the alternate Display format which renders the full cause chain
    // as "outer: inner: root cause".
    miette::miette!("{err:#}")
}

/// Write a lockfile to disk with a header comment.
///
/// The lockfile is prefixed with a comment indicating it is auto-generated
/// and should not be manually edited.
#[allow(dead_code)]
pub(crate) async fn write_lock_file<P: AsRef<Path>>(
    path: P,
    lock: &Lockfile,
) -> std::io::Result<()> {
    let header = "# This file is automatically generated by wasm(1).\n\
                  # It should not be manually edited.\n";
    let body = toml::to_string_pretty(lock).expect("failed to serialize lock file");
    let contents = format!("{header}\n{body}");
    tokio::fs::write(path.as_ref(), contents).await
}
