use std::path::Path;

use wasm_manifest::Lockfile;

/// Write a lockfile to disk with a header comment.
///
/// The lockfile is prefixed with a comment indicating it is auto-generated
/// and should not be manually edited.
pub(crate) async fn write_lock_file<P: AsRef<Path>>(
    path: P,
    lock: &Lockfile,
) -> std::io::Result<()> {
    let header = "# This file is automatically generated by wasm(1).\n\
                  # It should not be manually edited.\n";
    let body = toml::to_string_pretty(lock).expect("failed to serialize lock file");
    let contents = format!("{header}\n{body}");
    tokio::fs::write(path.as_ref(), contents).await
}
